### ISSUE TITLE
Small error in HA Embedding instructions

### ISSUE THREAD

**Issue by rpitera** [hassio-addons/addon-tautulli#9]
In the instructions to embed Tautulli in Home Assistant, the example config lists:

```
panel_iframe:
  tautulli:
    title: Tautulli
    icon: mdi:tautulli
    url: http://addres.to.your.hass.io:8181
```

There is no such MDI Icon.   Maybe use mdi:filmstrip instead?   Otherwise, thanks for this great addon.
